[package]
name = "egui_gpu_plot"
version = "0.1.0"
edition = "2021"

[[example]]
name = "lorenz"

[dependencies]
bytemuck = "1.12"

eframe = { version = "0.31", features = ["wgpu"] }
egui = "0.31"
egui_plot = "0.31"
egui-wgpu = "0.31"
ecolor = "0.31"
